apiVersion: v1
kind: Secret
metadata:
  name: firebase-admin
type: Opaque
stringData:
  firebase-adminsdk.json: |
    {
      "type": "service_account",
      "project_id": "367483555455",
      "private_key_id": "cd2b8cdf3a12df576e1e07397aab1f26f4f96409",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC43RK7q7Z8o2+l\nzUV83J7Q2paDjHnq021RUs2gY0ChdOjzsyTTowvzuHyW4DrnutgnREbYaj+f+eZ+\nOl99CU6axIKq+aLX0mIf0S9133UsanyeeBhQKigk8T3rvi00j+ho30uLVRmGqNP8\nw+7ItCaw0ZcOOB3HuykTGSpOFcaCZ6TwoBrwIUuXUkDRv2P7e+WNmWM4B42AD/lr\njJNuKSFB06CPV92SiCCuqTA7e53hTyfb61dYFgSflPQ2YT6iIfj6cg6Hqew3r4h/\nL9p2/mQqG15Ax/52p998sIhoRm5xzWEeKtpkLpzjaHVO75QIPsjTuLnHymHFuoqQ\nsdb3gRq5AgMBAAECggEALqXul7fdXTc6saqKSdc8JjS6fWiBzU1bzQUpiTrycKuZ\nKwG+Hb+LgQ1BNytPAfGmoMX8YJjzBDHhxWGCfgFOugQzeuRygKaAh0nYgZSJM1ON\nrcldTUFODwBnISlEq/pSacBLBlZLkizhDWv9wdyf1MeWqApmDWP/meekQr8A8B+8\ndQjUQ4f0yOd/lN5hoO8WQzmJU2e2NpKBqdASn1ZUsUNVNfrZv78+DCXS68nA0C2j\ndVxl8oBmNARhsiwOg0XibkSo1zbldNHnVck6knbQ4/xSZX874yMzC52fG4YNpjib\n61beyzlYNKU+r4v5b/CYlpYFJzDClA1mdAaqvxGpFwKBgQDcYj65d5+zUPAtp6NX\nZjGjSIoqYabnCfwi/k/3bnuFRpF/QmsAv9SsTCyph6szclYOYg2sZM8cEW+OrqvT\nIUfD4+W5LlaxsQNiVlU4lGRyQ63YmhdqVMFgFLBq2RkVNH7+OUcHgj40NWl1GSR4\nZNImv8/Mee7se16JnuMb9DqQMwKBgQDWvUe/wO8AmrauTI+RhytD0hfEJH8i3o5f\nlvuKUm9PSNX21Yb8QO0e5fW1xnb8hN7GEemRLX3l2PmVwdMFw4ymSm2Kw7ccSFgy\n45CQGnpgMq3J+4aVUZHRxTHtMpbFshVFUgboNGwGeZLuFhh+GZ0H4v/Ne1a4k7of\nL5IdTpRNYwKBgHYnNfm5aKV6f0n61lfFMleYTHrsX87+S293aOf/E7ogW2Ee+r8s\nGZlGPaumUOMEKZ8Mcsg6Q8+IiYa1nulSrmcXh9IARfp+LJJMNuReqnuYTVwTQPqA\n9ivM68hdHFWCD5O8oZgk+7SB7kgZcrQZWZHsxDucI7wlaEngJWKXTc6BAoGAN05S\nn1lidOZj7Go9g76rbvE6O8Mml2V4h7gMGuj2UBYzPTprZKaYK6AQc3ulA455Dcxp\nOoHb7gm+5kogPljJ7b43jkiv7XHYfWrMvcCECiijR+UnGWgDxWIjZLLl0A74mXzx\n2HY/6D8Bj55TOo8AOZrGRTbh8/HgOs32tOObIH8CgYEAgExvjkhhUQ2uhJLAAUt5\nxxfZxtxI6XbgQUlfzIqAh2PZiKBmkSrwGOpgEEfBsnzIykGrK5K8vgLqX1IzXc+B\nYRrEz2rlfptO+EjBqAJY3kLdRlldUHpkg9A0ZyU1ekjPHxHoQoa3otBPuS9k8Hli\ncJ+gBf/EdN/iRXGshSEipnM=\n-----END PRIVATE KEY-----\n",
      "client_email": "firebase-adminsdk-fbsvc@arksaas.iam.gserviceaccount.com",
      "client_id": "116509606136989060069",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "measurementId": "G-3EZ5STEM2L",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40arksaas.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }


