apiVersion: v1
kind: Secret
metadata:
  name: firebase-admin
type: Opaque
stringData:
  firebase-adminsdk.json: |
    {
      "type": "service_account",
      "project_id": "arksaas",
      "private_key_id": "393010c034559e51ef4082c2290bed45283dca2e",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDKEtZFBuQTfDgt\ndoPgpxQnM14YF35LjL04PpzixjVeRJyx24/gS2Vi+mKJKK0g4BaRt1CRpMyyHdkD\n3bBtTKWau8Z+dl7q+PFIMKLokEjd0vhYlg40eHm+IfseGAotO0U0HSxJuSxn5m+e\nHoK5OGIRXbUfjuQfWw2QJ+d7xBzSjukC1DmGn1arUb3Uvtnd3CE4/a+54RpFfgpk\nSHcpnFRLBtoTXG3YnO1LuBdddyRNamXJG8LIf1rM99lBmFY6wPA25FGNmuxx7IKP\nRfcxNqgVpaxgqhef14GonPbgNPI0MxSARfSwffDD0cqpCLe8WR1PHyYlAbQti81Q\nKWV64C07AgMBAAECggEAAZQsSY/3c0aatbSn3tKsVXzUkQIGvT7+bh/Iu6k60HYM\nJv0M97X+qSHkaCQRXeRgKFV8oqZ1gIhTrl9xfI9mWpeOeZWhzCM9HHHOrHfCuAm4\nn/THGPVyVfMwh+HyEMmsxpg0Imt8bentjHy6Z1x4splA3yukNyc0HasEF7sYG0IO\ncIX/bEtN89iVeFYn+O3sWgm2dqHTn0z/pYc2l1EA69+Z/2rMk6zuxr/HmilL9bGp\nBC8+RBEG1lTIzai1QAaWF1MfUtVolnCZHRFyhIk8katHpUb+T2UIColuX+8AnHAq\n6bGEUWJWlZ8THCqhsaxPhE8dVdEeyUpJFxukX3ju8QKBgQD/U4NlXA7c/oBzViYR\naj4u8NIh4jtQYgSm6l/ZO9E8GKzg8tme9Hw0JxJ8jGTTvnPf7eZK5zo8qD55EKiF\nTralajh3YyoOP2xDb7VLu8tdUYjG+HdCscd8p9bj7VR8nOx/9uTm9s4bIlJ9nkA9\nzlMHsP4z2c7TjDBTgItoRaazywKBgQDKm1lCohi2eS6LYyTcVvf+o1+5ldvw4DYW\n0fqAdrONQy0u2ZBpUvIB+phc0TrtNn23wtMB812RwK2Q8EYopI9iqODSOOJunqgB\n3NLg2sivT+FMLKI+1DDvJXQeMqm0cKOwGOA4ZlvPPwNrA4Veb1zQTnz7XipahEv0\nrA7OqT6eUQKBgH+SUZ+OTJrcyn9WNvUSmXlIuCVX7PzvzJU9m6Blw9h8F7zZeiRy\n0bAZKaJzX1lw2mKzchJQ0AdIpNZGnXzl5Fpn5Ui5kmTGCaj0Iqhxb130BBwuPyBi\nxWKiVbtSdJlCquQRDzPbcwWZs4+yRzTaZx/7rjdoB3AppmfCXWU/D9jbAoGBAJ8Z\nrtZshAuGzc4XZPLCOKx1js4lqDlXWCJDcfs/O3BKuEh6ALU0tWZoaw04IJX2nHKZ\nQync+jVioOmYRP/VeeN3ylRK50UGwdf0mISKSd2hVMKEqkO8TVD+kFjGYA2aBnBa\nmHixqJbuXLjEYw7tVG0ftXWPVKMQELVqB5axwMKBAoGBANrqknN4xwVHzehe1K4k\nnMlJWm8smTkXa92ynQkdMVCnpYyg7Qe6WS+tUaSLgiol9UbdiMk9ozwOBtHGfWdN\n7nFmYw0vtPtcIziERGXAti3qX9qYO5FJplHsPKO8gyr60jiH5OFP5R7RaCGsVb6U\nkmFtMQOwyRqbvcPxErp/1/pT\n-----END PRIVATE KEY-----\n",
      "client_email": "firebase-adminsdk-fbsvc@arksaas.iam.gserviceaccount.com",
      "client_id": "116509606136989060069",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40arksaas.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }



