apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "CHANGE_ME",
          "password": "CHANGE_ME",
          "auth": "Q0hBTkdFX01FOkNIQU5HRV9NRQ=="
        }
      }
    }
