apiVersion: v1
kind: Secret
metadata:
  name: arksaas-runtime-secrets
type: Opaque
stringData:
  ConnectionStrings__Admin: Server=databasevm,1433;Database=ARKSAAS_ADMIN;User Id=sa;Password=3ct1vyTVpxsQyUiBVroY;TrustServerCertificate=True;
  ConnectionStrings__Identity: Server=databasevm,1433;Database=ARKSAAS_IDENTITY;User Id=sa;Password=3ct1vyTVpxsQyUiBVroY;TrustServerCertificate=True;
  ConnectionStrings__Billing: Server=databasevm,1433;Database=ARKSAAS_BILLING;User Id=sa;Password=3ct1vyTVpxsQyUiBVroY;TrustServerCertificate=True;
  ConnectionStrings__Notification: Server=databasevm,1433;Database=ARKSAAS_NOTIFICATION;User Id=sa;Password=3ct1vyTVpxsQyUiBVroY;TrustServerCertificate=True;
  ConnectionStrings__Permission: Server=databasevm,1433;Database=ARKSAAS_PERMISSION;User Id=sa;Password=3ct1vyTVpxsQyUiBVroY;TrustServerCertificate=True;
  ConnectionStrings__ServerProvisioning: Server=databasevm,1433;Database=ARKSAAS_SERVER_PROVISIONING;User Id=sa;Password=3ct1vyTVpxsQyUiBVroY;TrustServerCertificate=True;
  ConnectionStrings__Agent: Server=databasevm,1433;Database=ARKSAAS_AGENT;User Id=sa;Password=3ct1vyTVpxsQyUiBVroY;TrustServerCertificate=True;
  ConnectionStrings__MongoDB: mongodb://admin:3ct1vyTVpxsQyUiBVroY@databasevm:27017/arksaas?authSource=admin&retryWrites=true&w=majority
  ConnectionStrings__Redis: databasevm:6379,password=3ct1vyTVpxsQyUiBVroY,abortConnect=false
  InternalApi__ApiKey: arksaas-local-dev-internal-api-key
  Services__Agent__InternalApiKey: arksaas-local-dev-internal-api-key
  Stripe__SecretKey: sk_test_51THKaJHTKNxDQE73L964hlE78ob8mnWmqdrS6YA96AWD4sqZxxMVduZoT7G2zFImYyk8a6Qkh20YvDARnlJ6N2Qe00odPtgG05
  Stripe__WebhookSigningSecret: whsec_h2q3wTenqgk0fTO6jN370g2xszwctDeW
  Seq__ApiKey: sjdFRFPCkftYgj4i7jhu
