apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: arksaas-prod-updater
  namespace: argocd
spec:
  namespace: argocd
  commonUpdateSettings:
    updateStrategy: newest-build
  writeBackConfig:
    method: git
    gitConfig:
      writeBackTarget: kustomization
  applicationRefs:
    - namePattern: arksaas-prod
      images:
        - alias: gateway
          imageName: ghcr.io/hantse/arksaas-gateway
          commonUpdateSettings:
            allowTags: regexp:^[0-9a-f]{40}$
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: ghcr.io/hantse/arksaas-gateway
        - alias: admin
          imageName: ghcr.io/hantse/arksaas-admin-service
          commonUpdateSettings:
            allowTags: regexp:^[0-9a-f]{40}$
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: ghcr.io/hantse/arksaas-admin-service
        - alias: agent
          imageName: ghcr.io/hantse/arksaas-agent-service
          commonUpdateSettings:
            allowTags: regexp:^[0-9a-f]{40}$
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: ghcr.io/hantse/arksaas-agent-service
        - alias: billing
          imageName: ghcr.io/hantse/arksaas-billing-service
          commonUpdateSettings:
            allowTags: regexp:^[0-9a-f]{40}$
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: ghcr.io/hantse/arksaas-billing-service
        - alias: data
          imageName: ghcr.io/hantse/arksaas-data-service
          commonUpdateSettings:
            allowTags: regexp:^[0-9a-f]{40}$
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: ghcr.io/hantse/arksaas-data-service
        - alias: identity
          imageName: ghcr.io/hantse/arksaas-identity-service
          commonUpdateSettings:
            allowTags: regexp:^[0-9a-f]{40}$
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: ghcr.io/hantse/arksaas-identity-service
        - alias: llm
          imageName: ghcr.io/hantse/arksaas-llm-service
          commonUpdateSettings:
            allowTags: regexp:^[0-9a-f]{40}$
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: ghcr.io/hantse/arksaas-llm-service
        - alias: notification
          imageName: ghcr.io/hantse/arksaas-notification-service
          commonUpdateSettings:
            allowTags: regexp:^[0-9a-f]{40}$
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: ghcr.io/hantse/arksaas-notification-service
        - alias: permission
          imageName: ghcr.io/hantse/arksaas-permission-service
          commonUpdateSettings:
            allowTags: regexp:^[0-9a-f]{40}$
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: ghcr.io/hantse/arksaas-permission-service
        - alias: server-provisioning
          imageName: ghcr.io/hantse/arksaas-server-provisioning-service
          commonUpdateSettings:
            allowTags: regexp:^[0-9a-f]{40}$
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: ghcr.io/hantse/arksaas-server-provisioning-service

