apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arksaas-prod
labels:
  - pairs:
      app.kubernetes.io/part-of: arksaas
resources:
  - serviceaccount.yaml
  - ingress.yaml
  - configs/arksaas-public-config.yaml
  - secrets/runtime-secrets.yaml
  - secrets/firebase-admin-secret.yaml
  - services/gateway/workload.yaml
  - services/identity/workload.yaml
  - services/admin/workload.yaml
  - services/frontend/workload.yaml
  - services/agent/workload.yaml
  - services/billing/workload.yaml
  - services/data/workload.yaml
  - services/llm/workload.yaml
  - services/notification/workload.yaml
  - services/permission/workload.yaml
  - services/server-provisioning/workload.yaml
images:
  - name: ghcr.io/hantse/arksaas-gateway
    newName: ghcr.io/hantse/arksaas-gateway
    newTag: 2554e129b027b2c6d3efa8ada34b17167c7ecb0d
  - name: ghcr.io/hantse/arksaas-admin-service
    newName: ghcr.io/hantse/arksaas-admin-service
    newTag: 2554e129b027b2c6d3efa8ada34b17167c7ecb0d
  - name: ghcr.io/hantse/arksaas-agent-service
    newName: ghcr.io/hantse/arksaas-agent-service
    newTag: 2554e129b027b2c6d3efa8ada34b17167c7ecb0d
  - name: ghcr.io/hantse/arksaas-billing-service
    newName: ghcr.io/hantse/arksaas-billing-service
    newTag: c043cbc5710e19eed4c2c1defe22042d90a918e3
  - name: ghcr.io/hantse/arksaas-data-service
    newName: ghcr.io/hantse/arksaas-data-service
    newTag: 2554e129b027b2c6d3efa8ada34b17167c7ecb0d
  - name: ghcr.io/hantse/arksaas-identity-service
    newName: ghcr.io/hantse/arksaas-identity-service
    newTag: 2554e129b027b2c6d3efa8ada34b17167c7ecb0d
  - name: ghcr.io/hantse/arksaas-llm-service
    newName: ghcr.io/hantse/arksaas-llm-service
    newTag: 2554e129b027b2c6d3efa8ada34b17167c7ecb0d
  - name: ghcr.io/hantse/arksaas-notification-service
    newName: ghcr.io/hantse/arksaas-notification-service
    newTag: 2554e129b027b2c6d3efa8ada34b17167c7ecb0d
  - name: ghcr.io/hantse/arksaas-permission-service
    newName: ghcr.io/hantse/arksaas-permission-service
    newTag: 2554e129b027b2c6d3efa8ada34b17167c7ecb0d
  - name: ghcr.io/hantse/arksaas-server-provisioning-service
    newName: ghcr.io/hantse/arksaas-server-provisioning-service
    newTag: 2554e129b027b2c6d3efa8ada34b17167c7ecb0d
  - name: ghcr.io/hantse/orkestrix-frontend
    newName: ghcr.io/hantse/orkestrix-frontend
    newTag: sha-72fdc890b598fd6997bb97fb33336271cb3c3e8e
  - name: ghcr.io/hantse/arksaas-server-provisioning-worker
    newName: ghcr.io/hantse/arksaas-server-provisioning-worker
    newTag: 2554e129b027b2c6d3efa8ada34b17167c7ecb0d
