apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arksaas-prod
labels:
  - pairs:
      app.kubernetes.io/part-of: arksaas
resources:
  - serviceaccount.yaml
  - ingress.yaml
  - configs/arksaas-public-config.yaml
  - secrets/runtime-secrets.yaml
  - secrets/firebase-admin-secret.yaml
  - services/gateway/workload.yaml
  - services/identity/workload.yaml
  - services/admin/workload.yaml
  - services/frontend/workload.yaml
  - services/agent/workload.yaml
  - services/billing/workload.yaml
  - services/data/workload.yaml
  - services/llm/workload.yaml
  - services/notification/workload.yaml
  - services/permission/workload.yaml
  - services/server-provisioning/workload.yaml
images:
  - name: ghcr.io/hantse/arksaas-gateway
    newName: ghcr.io/hantse/arksaas-gateway
    newTag: 0642cd74044649100bc635480d2062db7d9bd038
  - name: ghcr.io/hantse/arksaas-admin-service
    newName: ghcr.io/hantse/arksaas-admin-service
    newTag: 0642cd74044649100bc635480d2062db7d9bd038
  - name: ghcr.io/hantse/arksaas-agent-service
    newName: ghcr.io/hantse/arksaas-agent-service
    newTag: 0642cd74044649100bc635480d2062db7d9bd038
  - name: ghcr.io/hantse/arksaas-billing-service
    newName: ghcr.io/hantse/arksaas-billing-service
    newTag: 0642cd74044649100bc635480d2062db7d9bd038
  - name: ghcr.io/hantse/arksaas-data-service
    newName: ghcr.io/hantse/arksaas-data-service
    newTag: 0642cd74044649100bc635480d2062db7d9bd038
  - name: ghcr.io/hantse/arksaas-identity-service
    newName: ghcr.io/hantse/arksaas-identity-service
    newTag: 0642cd74044649100bc635480d2062db7d9bd038
  - name: ghcr.io/hantse/arksaas-llm-service
    newName: ghcr.io/hantse/arksaas-llm-service
    newTag: 0642cd74044649100bc635480d2062db7d9bd038
  - name: ghcr.io/hantse/arksaas-notification-service
    newName: ghcr.io/hantse/arksaas-notification-service
    newTag: 0642cd74044649100bc635480d2062db7d9bd038
  - name: ghcr.io/hantse/arksaas-permission-service
    newName: ghcr.io/hantse/arksaas-permission-service
    newTag: 0642cd74044649100bc635480d2062db7d9bd038
  - name: ghcr.io/hantse/arksaas-server-provisioning-service
    newName: ghcr.io/hantse/arksaas-server-provisioning-service
    newTag: 0642cd74044649100bc635480d2062db7d9bd038
  - name: ghcr.io/hantse/orkestrix-frontend
    newName: ghcr.io/hantse/orkestrix-frontend
    newTag: sha-191f8792d92bcdd1880307d4dce4351b28ffc32e
