apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arksaas-prod
labels:
  - pairs:
      app.kubernetes.io/part-of: arksaas
resources:
  - serviceaccount.yaml
  - ingress.yaml
  - configs/arksaas-public-config.yaml
  - secrets/runtime-secrets.yaml
  - secrets/firebase-admin-secret.yaml
  - services/gateway/workload.yaml
  - services/identity/workload.yaml
  - services/admin/workload.yaml
  - services/frontend/workload.yaml
  - services/agent/workload.yaml
  - services/billing/workload.yaml
  - services/data/workload.yaml
  - services/llm/workload.yaml
  - services/notification/workload.yaml
  - services/permission/workload.yaml
  - services/server-provisioning/workload.yaml
images:
  - name: ghcr.io/hantse/arksaas-gateway
    newName: ghcr.io/hantse/arksaas-gateway
    newTag: f0e754d6704cf78fdb04bc1e4862b430d416d3ca
  - name: ghcr.io/hantse/arksaas-admin-service
    newName: ghcr.io/hantse/arksaas-admin-service
    newTag: 994c04a481b546cab5bd6e34c89d0bd3cb6c4d4c
  - name: ghcr.io/hantse/arksaas-agent-service
    newName: ghcr.io/hantse/arksaas-agent-service
    newTag: f0e754d6704cf78fdb04bc1e4862b430d416d3ca
  - name: ghcr.io/hantse/arksaas-billing-service
    newName: ghcr.io/hantse/arksaas-billing-service
    newTag: f0e754d6704cf78fdb04bc1e4862b430d416d3ca
  - name: ghcr.io/hantse/arksaas-data-service
    newName: ghcr.io/hantse/arksaas-data-service
    newTag: f0e754d6704cf78fdb04bc1e4862b430d416d3ca
  - name: ghcr.io/hantse/arksaas-identity-service
    newName: ghcr.io/hantse/arksaas-identity-service
    newTag: f0e754d6704cf78fdb04bc1e4862b430d416d3ca
  - name: ghcr.io/hantse/arksaas-llm-service
    newName: ghcr.io/hantse/arksaas-llm-service
    newTag: f0e754d6704cf78fdb04bc1e4862b430d416d3ca
  - name: ghcr.io/hantse/arksaas-notification-service
    newName: ghcr.io/hantse/arksaas-notification-service
    newTag: f0e754d6704cf78fdb04bc1e4862b430d416d3ca
  - name: ghcr.io/hantse/arksaas-permission-service
    newName: ghcr.io/hantse/arksaas-permission-service
    newTag: f0e754d6704cf78fdb04bc1e4862b430d416d3ca
  - name: ghcr.io/hantse/arksaas-server-provisioning-service
    newName: ghcr.io/hantse/arksaas-server-provisioning-service
    newTag: f0e754d6704cf78fdb04bc1e4862b430d416d3ca
  - name: ghcr.io/hantse/orkestrix-frontend
    newName: ghcr.io/hantse/orkestrix-frontend
    newTag: sha-0d49e3541f4f0d0f5cb50d1ec2c6370f4faa84e8
  - name: ghcr.io/hantse/arksaas-server-provisioning-worker
    newName: ghcr.io/hantse/arksaas-server-provisioning-worker
    newTag: f0e754d6704cf78fdb04bc1e4862b430d416d3ca
